import streamlit as st
import torch
from diffusers import StableDiffusionPipeline
from deep_translator import GoogleTranslator

st.set_page_config(page_title="Xmugi AI")

st.title("Xmugi AI")

@st.cache_resource
def load_pipeline():
    pipe = StableDiffusionPipeline.from_pretrained(
        "segmind/small-sd",
        torch_dtype=torch.float32,
        low_cpu_mem_usage=True
    )
    return pipe

user_input = st.text_input("", "a detailed portrait of a fantasy anime girl, masterpiece")

if st.button("Generate Image"):
    if user_input.strip():
        translated_prompt = GoogleTranslator(source='auto', target='en').translate(user_input)
        
        if translated_prompt.lower() != user_input.lower():
            st.info(f"Translated Prompt: {translated_prompt}")

        progress_bar = st.progress(0)
        status_text = st.empty()
        
        total_steps = 20

        def callback_fn(step, timestep, latents):
            current_step = step + 1
            percent = int((current_step / total_steps) * 100)
            progress_bar.progress(percent)
            status_text.text(f"Generating: {percent}/100")

        pipe = load_pipeline()
        
        image = pipe(
            translated_prompt,
            height=256,
            width=256,
            num_inference_steps=total_steps,
            callback=callback_fn,
            callback_steps=1
        ).images[0]

        progress_bar.progress(100)
        status_text.text("Generating: 100/100 - Completed!")
        st.image(image, caption=f"Generated by Xmugi AI ({translated_prompt})")
